routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;

Route::group(['middleware' => ['auth', 'check_role'], 'prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');

    Route::resource('users', 'UserController');
    Route::delete('users_mass_destroy', 'UserController@massDestroy')->name('users.mass_destroy');

    Route::resource('roles', 'RoleController');
    Route::delete('roles_mass_destroy', 'RoleController@massDestroy')->name('roles.mass_destroy');

    Route::resource('permissions', 'PermissionController');
    Route::delete('permissions_mass_destroy', 'PermissionController@massDestroy')->name('permissions.mass_destroy');

    Route::get('articles/search', 'ArticleController@search')->name('articles.search');
    Route::resource('articles', 'ArticleController');

    Route::resource('categories', 'CategoryController');

    Route::resource('pages', 'PageController');

    Route::resource('menus', 'MenuController');

    Route::resource('tools', 'ToolController');

    Route::resource('slides', 'SlideController');

    Route::resource('comments', 'CommentController');

    Route::resource('messages', 'MessageController');

    Route::get('complaints/search', 'ComplaintController@search')->name('complaints.search');
    Route::resource('complaints', 'ComplaintController');

    Route::get('file-manager', 'FileManagerController@index')->name('file-manager');

    Route::group(['prefix' => 'filemanager'], function () {
        Lfm::routes();
    });

    Route::get('attachments/{filename}', function ($filename) {
        $full_path = storage_path('app/attachments/' . $filename);

        if (!File::exists($full_path)) {
            abort(404);
        }

        $file = File::get($full_path);
        $type = File::mimeType($full_path);

        return response($file, 200)->header("Content-Type", $type);
    })->name('attachment');
});

Route::group(['as' => 'site.', 'namespace' => 'Site', 'middleware' => 'visit'], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::get('/complaint', 'ComplaintController@create')->name('complaint');
    Route::post('/complaints', 'ComplaintController@store')->name('complaints.store');

    Route::get('pages/{page}', 'PageController@show')->name('pages.show');

    Route::get('articles/search', 'ArticleController@search')->name('articles.search');
    Route::get('articles/{article}', 'ArticleController@show')->name('articles.show');
    Route::get('articles', 'ArticleController@index')->name('articles.index');
    Route::post('articles/{article}/comments', 'CommentController@store')->name('comments.store');

    Route::get('tags/{tag}', 'TagController@show')->name('tags.show');

    Route::get('categories/{category}', 'CategoryController@show')->name('categories.show');

    Route::post('messages', 'MessageController@store')->name('messages.store');
});

Route::group(['middleware' => 'auth', 'namespace' => 'Auth'], function () {

    Route::post('/logout', 'AuthController@logout')->name('logout');
});


Route::get('test', function () {
    return 'true';
});

resources/views/admin/file-manager.blade.php
@extends('admin.partials.master')
@section('admin.title','مدیریت فایل')
@section('main')
<iframe class="w-100" style="border: none; height: 500px;" src="{{ route('admin.unisharp.lfm.show',['type' => 'image']) }}"></iframe>
@endsection

resources/views/admin/home.blade.php
@extends('admin.partials.master')
@section('admin.title', 'داشبورد')
@section('main')
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="card text-white bg-success mb-3">
                    <div class="card-body">
                        <h5 class="card-title">
                            <span class="material-icons">person</span>
                            <span>عنوان</span>
                        </h5>
                        <p class="card-text">متن مثال</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="card text-white bg-warning mb-3">
                    <div class="card-body">
                        <h5 class="card-title">
                            <span class="material-icons">person</span>
                            <span>عنوان</span>
                        </h5>
                        <p class="card-text">متن مثال</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="card text-white bg-info mb-3">
                    <div class="card-body">
                        <h5 class="card-title">
                            <span class="material-icons">person</span>
                            <span>عنوان</span>
                        </h5>
                        <p class="card-text">متن مثال</p>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="card text-white bg-danger mb-3">
                    <div class="card-body">
                        <h5 class="card-title">
                            <span class="material-icons">person</span>
                            <span>عنوان</span>
                        </h5>
                        <p class="card-text">متن مثال</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header bg-success text-white d-flex justify-content-between align-items-center">
                <span>نظرات امروز</span>
                <a class="btn btn-sm btn-flat-light" href="{{ route('admin.comments.index') }}">مشاهده همه</a>
            </div>
            <div class="card-body">
                @if (count($comments))
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-hover">
                        <thead>
                            <tr>
                                <th>
                                    متن
                                </th>
                                <th>
                                    خبر
                                </th>
                                <th>
                                    وضعیت
                                </th>
                                <th>
                                    تاریخ ایجاد
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($comments as $key => $comment)
                                <tr>
                                    <td>
                                    <div class="text-truncate {{ $comment->readed ? '' : 'font-weight-bold' }}" style="width: 200px;">
                                            {{ $comment->body ?? '' }}
                                        </div>
                                    </td>
                                    <td>
                                        <a
                                            href="{{ route('admin.articles.show', $comment->article) }}">{{ $comment->article->title }}</a>
                                    </td>
                                    <td>
                                        @if ($comment->published)
                                            <span class="badge badge-success badge-pill py-1 px-2"> تایید شده </span>
                                        @else
                                            <span class="badge badge-warning text-white badge-pill py-1 px-2"> تایید نشده </span>
                                        @endif
                                    </td>
                                    <td>
                                        {{ verta($comment->created_at)->format('j F Y | H:i') ?? '' }}
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                @else
                <div>امروز نظری ثبت نشده است.</div>
                @endif
            </div>
        </div>
        <div class="card mt-3">
            <div class="card-header bg-warning text-white d-flex justify-content-between align-items-center">
                <span>پیام های امروز</span>
                <a class="btn btn-sm btn-flat-light" href="{{ route('admin.messages.index') }}">مشاهده همه</a>
            </div>
            <div class="card-body">
                @if (count($messages))
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        متن
                                    </th>
                                    <th>
                                        تاریخ ایجاد
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($messages as $key => $message)
                                    <tr>
                                        <td>
                                            <div class="text-truncate {{ $message->readed ? '' : 'font-weight-bold' }}"
                                                style="width: 600px;">
                                                {{ $message->body ?? '' }}
                                            </div>
                                        </td>
                                        <td>
                                            {{ verta($message->created_at)->format('j F Y | H:i') ?? '' }}
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <div>امروز پیامی ثبت نشده است.</div>
                @endif
            </div>
        </div>
        <div class="card mt-3">
            <div class="card-header bg-info text-white d-flex justify-content-between align-items-center">
                <span>شکایات امروز</span>
                <a class="btn btn-sm btn-flat-light" href="{{ route('admin.complaints.index') }}">مشاهده همه</a>
            </div>
            <div class="card-body">
                @if (count($complaints))
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        کد پیگیری
                                    </th>
                                    <th>
                                        نام شاکی
                                    </th>
                                    <th>
                                        تلفن شاکی
                                    </th>
                                    <th>
                                        وضعیت
                                    </th>
                                    <th>
                                        تاریخ ایجاد
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($complaints as $key => $complaint)
                                    <tr>
                                        <td>
                                            <div class="text-truncate {{ $complaint->readed ? '' : 'font-weight-bold' }}">
                                                {{ $complaint->code ?? '' }}
                                            </div>
                                        </td>
                                        <td>
                                            {{ $complaint->shaki_name ?? '' }}
                                        </td>
                                        <td>
                                            {{ $complaint->shaki_tel ?? '' }}
                                        </td>
                                        <td>
                                            @switch($complaint->status)
                                                @case(App\Complaint::CREATED_STATUS)
                                                <span class="badge badge-info badge-pill py-1 px-2"> ثبت شده </span>
                                                @break
                                                @case(App\Complaint::PENDING_STATUS)
                                                <span class="badge badge-warning text-white badge-pill py-1 px-2"> در حال پیگیری
                                                </span>
                                                @break
                                                @case(App\Complaint::DENIED_STATUS)
                                                <span class="badge badge-danger badge-pill py-1 px-2"> رد شده </span>
                                                @break
                                                @case(App\Complaint::ACCEPTED_STATUS)
                                                <span class="badge badge-success badge-pill py-1 px-2"> پذیرفته شده </span>
                                                @break
                                                @case(App\Complaint::PROBLEM_STATUS)
                                                <span class="badge badge-danger badge-pill py-1 px-2"> اطلاعات ناقص </span>
                                                @break
                                                @case(App\Complaint::FINISHED_STATUS)
                                                <span class="badge badge-success badge-pill py-1 px-2"> خاتمه یافته </span>
                                                @break
                                            @endswitch
                                        </td>
                                        <td>
                                            {{ verta($complaint->created_at)->format('j F Y | H:i') ?? '' }}
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <div>امروز شکایتی ثبت نشده است.</div>
                @endif
            </div>
        </div>
    </div>
@endsection