routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;

Route::group(['middleware' => ['auth', 'check_role'], 'prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');

    Route::resource('users', 'UserController');
    Route::delete('users_mass_destroy', 'UserController@massDestroy')->name('users.mass_destroy');

    Route::resource('roles', 'RoleController');
    Route::delete('roles_mass_destroy', 'RoleController@massDestroy')->name('roles.mass_destroy');

    Route::resource('permissions', 'PermissionController');
    Route::delete('permissions_mass_destroy', 'PermissionController@massDestroy')->name('permissions.mass_destroy');

    Route::get('articles/search', 'ArticleController@search')->name('articles.search');
    Route::resource('articles', 'ArticleController');

    Route::resource('categories', 'CategoryController');

    Route::resource('pages', 'PageController');

    Route::resource('menus', 'MenuController');

    Route::resource('tools', 'ToolController');

    Route::resource('slides', 'SlideController');

    Route::resource('comments', 'CommentController');

    Route::resource('messages', 'MessageController');

    Route::get('complaints/search', 'ComplaintController@search')->name('complaints.search');
    Route::resource('complaints', 'ComplaintController');

    Route::get('file-manager', 'FileManagerController@index')->name('file-manager');

    Route::group(['prefix' => 'filemanager'], function () {
        Lfm::routes();
    });

    Route::get('attachments/{filename}', function ($filename) {
        $full_path = storage_path('app/attachments/' . $filename);

        if (!File::exists($full_path)) {
            abort(404);
        }

        $file = File::get($full_path);
        $type = File::mimeType($full_path);

        return response($file, 200)->header("Content-Type", $type);
    })->name('attachment');
});

Route::group(['as' => 'site.', 'namespace' => 'Site', 'middleware' => 'visit'], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::get('/complaint', 'ComplaintController@create')->name('complaint');
    Route::post('/complaints', 'ComplaintController@store')->name('complaints.store');

    Route::get('pages/{page}', 'PageController@show')->name('pages.show');

    Route::get('articles/search', 'ArticleController@search')->name('articles.search');
    Route::get('articles/{article}', 'ArticleController@show')->name('articles.show');
    Route::get('articles', 'ArticleController@index')->name('articles.index');
    Route::post('articles/{article}/comments', 'CommentController@store')->name('comments.store');

    Route::get('tags/{tag}', 'TagController@show')->name('tags.show');

    Route::get('categories/{category}', 'CategoryController@show')->name('categories.show');

    Route::post('messages', 'MessageController@store')->name('messages.store');
});

Route::group(['middleware' => 'auth', 'namespace' => 'Auth'], function () {

    Route::post('/logout', 'AuthController@logout')->name('logout');
});


Route::get('test', function () {
    return 'true';
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Pishran\LaravelPersianSlug\HasPersianSlug;
use Shetabit\Visitor\Traits\Visitable;
use Spatie\Sluggable\SlugOptions;
use Spatie\Tags\HasTags;

/**
 * App\Article
 *
 * @property int $id
 * @property int $user_id
 * @property int $category_id
 * @property string $title
 * @property string $slug
 * @property string|null $body
 * @property string|null $excerpt
 * @property string|null $image
 * @property string|null $seo_title
 * @property \Illuminate\Database\Eloquent\Collection|\Spatie\Tags\Tag[] $tags
 * @property string|null $meta_description
 * @property string|null $meta_keywords
 * @property int $featured
 * @property int $published
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\Category $category
 * @property-read int|null $tags_count
 * @property-read \App\User $user
 * @method static \Illuminate\Database\Eloquent\Builder|Article newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Article newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Article query()
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereBody($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereCategoryId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereExcerpt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereFeatured($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereMetaDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereMetaKeywords($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article wherePublished($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereSeoTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereTags($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article whereUserId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Article withAllTags($tags, $type = null)
 * @method static \Illuminate\Database\Eloquent\Builder|Article withAllTagsOfAnyType($tags)
 * @method static \Illuminate\Database\Eloquent\Builder|Article withAnyTags($tags, $type = null)
 * @method static \Illuminate\Database\Eloquent\Builder|Article withAnyTagsOfAnyType($tags)
 * @mixin \Eloquent
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Comment[] $comments
 * @property-read int|null $comments_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\Shetabit\Visitor\Models\Visit[] $visitLogs
 * @property-read int|null $visit_logs_count
 */
class Article extends Model
{
    use HasTags, HasPersianSlug, Visitable;

    protected $fillable = [
        'user_id',
        'category_id',
        'title',
        'seo_title',
        'excerpt',
        'body',
        'image',
        'meta_description',
        'meta_keywords',
        'published',
        'featured',
    ];


    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

    public function tagsToString()
    {
        $result = "";

        foreach ($this->tags as $key => $tag)

            if ($key == count($this->tags) - 1)
                $result .= $tag->name ;
            else
                $result .= $tag->name . ',';

        return $result;
    }


    public function sortedComments($orderBy)
    {
        return $this->Comments()
            ->orderBy('comments.created_at', $orderBy)
            ->get();
    }

}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreArticleRequest;
use App\Http\Requests\Admin\UpdateArticleRequest;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    public function index()
    {
        $this->authorize('view',Article::class );
        $articles = Article::latest()->paginate(10);

        return view('admin.articles.index', compact('articles'));
    }

    public function search(Request $request)
    {
        $articles = Article::where('title','LIKE',"%$request->q%")->latest()->paginate(10);
        $articles->appends(['q' => $request->q]);
        return view('admin.articles.index', compact('articles'));
    }

    /**
     * Show the form for creating new Article.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function create()
    {
        $this->authorize('create', Article::class);

        $categories = Category::all();

        return view('admin.articles.create', compact('categories'));
    }

    /**
     * Store a newly created Article in storage.
     *
     * @param  \App\Http\Requests\Admin\StoreArticleRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreArticleRequest $request)
    {
        $this->authorize('create', Article::class);

        $data = $request->all();
        $data['user_id'] = auth()->id();
        $article = Article::create($data);
        $article->attachTags(explode(',', $request->tags));

        return redirect()->route('admin.articles.index')->with(['msg' => 'خبر با موفقیت اضافه شد']);
    }


    /**
     * Show the form for editing Article.
     *
     * @param  int $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit(Article $article)
    {
        $this->authorize('update', $article);

        $categories = Category::all();

        return view('admin.articles.edit', compact('article', 'categories'));
    }

    /**
     * Update Article in storage.
     *
     * @param  \App\Http\Requests\Admin\UpdateArticleRequest $request
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateArticleRequest $request, Article $article)
    {
        $this->authorize('update', $article);

        $data = $request->all();
        $data['user_id'] = auth()->id();

        $article->syncTags(explode(',', $request->tags));
        $article->update($data);

        return redirect()->route('admin.articles.index')->with(['msg' => 'خبر با موفقیت ویرایش شد']);
    }


    /**
     * Remove Article from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Article $article)
    {
        $this->authorize('delete', $article);

        $article->delete();

        return redirect()->route('admin.articles.index')->with(['msg' => 'خبر با موفقیت حذف شد']);
    }

    public function show(Article $article)
    {
        $this->authorize('view', $article);

        return view('admin.articles.show', compact('article'));
    }

    /**
     * Delete all selected Article at once.
     *
     * @param Request $request
     */
    public function massDestroy()
    {
        Article::whereIn('id', request('ids'))->delete();

        return response()->noContent();
    }
}

app/Http/Controllers/Site/ArticleController.php
<?php

namespace App\Http\Controllers\Site;

use App\Article;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    public function index()
    {
        $articles = Article::where("published","=","1")->latest()->paginate(10);
        return view('site.article.index', compact('articles'));
    }

    public function show(Article $article)
    {
        $article->sortedComments('desc');
        return view('site.article.show', compact('article'));
    }

    public function search(Request $request)
    {
        $articles = Article::where('title', 'LIKE', "%$request->q%")->latest()->paginate(10);
        $articles->appends(['q' => $request->q]);
        return view('site.article.index', compact('articles'));
    }
}

resources/views/admin/articles/create.blade.php
@extends('admin.partials.master')
@section('admin.title', 'ایجاد خبر')
@section('main')

    <div>
        <div class="card-header">
            ایجاد خبر
        </div>

        <div class="card-body">
            <form action="{{ route('admin.articles.store') }}" method="POST">@csrf
                <div class="row">
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="title">عنوان</label>
                                    <div class="input-group">
                                        <span class="mdi mdi-format-title"> </span>
                                        <input type="text" name="title" value="{{ old('title') }}"
                                            class="form-control {{ $errors->has('title') ? ' is-invalid' : '' }}" id="title"
                                            placeholder="فارسی وارد شود" required>
                                        <div class="invalid-feedback">
                                            @error('title')
                                            {{ $message }}
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="mb-2" for="body"> محتوا </label>
                                    <textarea name="body" id="body"
                                        class="form-control {{ $errors->has('body') ? ' is-invalid' : '' }}">{{ old('body') }}</textarea>
                                    <div class="invalid-feedback">
                                        @error('body')
                                        {{ $message }}
                                        @enderror
                                    </div>
                                </div>
                                <input type="hidden" value="{{ auth()->id() }}" name="user_id" required>
                                <div class="form-group">
                                    <label class="mb-2" for="excerpt"> چکیده </label>
                                    <textarea id="excerpt" name="excerpt"
                                        class="form-control {{ $errors->has('excerpt') ? ' is-invalid' : '' }}"
                                        required>{{ old('excerpt') }}</textarea>
                                    <div class="invalid-feedback">
                                        @error('excerpt')
                                        {{ $message }}
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="mt-3">
                            <button class="btn btn-success" type="submit">
                                <span class="material-icons">
                                    save
                                </span> ذخیره
                            </button>
                        </div>

                    </div>
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-header bg-info text-white">
                                جزئیات
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label class="mb-1" for="category_id"> دسته بندی </label>
                                    <select name="category_id" id="category_id"
                                        class="form-control {{ $errors->has('category_id') ? ' is-invalid' : '' }}"
                                        required>
                                        @foreach ($categories as $category)
                                            <option value="{{ $category->id }}"
                                                {{ old('category_id') == $category->id ? 'selected' : '' }}>
                                                {{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                    <div class="invalid-feedback">
                                        @error('category_id')
                                        {{ $message }}
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="mb-1" for="published"> وضعیت </label>
                                    <select name="published" id="published"
                                        class="form-control {{ $errors->has('published') ? ' is-invalid' : '' }}" required>
                                        <option value="1" {{ old('published') == 1 ? 'selected' : '' }}>منتشر شده</option>
                                        <option value="0" {{ old('published') == 0 ? 'selected' : '' }}>پیشنویس</option>
                                    </select>
                                    <div class="invalid-feedback">
                                        @error('published')
                                        {{ $message }}
                                        @enderror
                                    </div>
                                </div>
                                <div class="custom-control custom-checkbox mt-4">
                                    <input name="featured" value="1" type="checkbox" class="custom-control-input"
                                        id="customCheck1" {{ old('featured') == 1 ? 'checked' : '' }}>
                                    <label class="custom-control-label" for="customCheck1">خبر ویژه</label>
                                </div>


                                <div class="form-group mt-4">
                                    <label for="tags">برچسب ها</label>
                                    <div class="input-group">
                                        <input type="text" name="tags" value="{{ old('tags') }}"
                                               class="form-control {{ $errors->has('tags') ? ' is-invalid' : '' }}" id="tags"
                                               placeholder="فارسی وارد شود">
                                        <div class="invalid-feedback">
                                            @error('tags')
                                            {{ $message }}
                                            @enderror
                                        </div>
                                    </div>
                                </div>



                            </div>
                        </div>
                        <div class="card mt-3">
                            <div class="card-header bg-info text-white">
                                تصویر
                            </div>

                            <div class="card-body">

                                    <span class="input-group-btn">
                                        <a id="lfm" data-input="thumbnail" data-preview="holder"
                                            class="btn btn-info text-white">
                                            <span class="material-icons">insert_photo</span> انتخاب
                                        </a>
                                    </span>
                                    <input placeholder="تصویر را انتخاب کنید" id="thumbnail" class="form-control"
                                        value="{{ old('image') }}" type="text" name="image" readonly required>

                            </div>
                        </div>

                        <div class="card mt-3">
                            <div class="card-header bg-success text-white">
                                محتوا سئو
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="seo_title">عنوان سئو</label>
                                    <div class="input-group">
                                        <span class="mdi mdi-format-title"> </span>
                                        <input type="text" name="seo_title" value="{{ old('seo_title') }}"
                                            class="form-control {{ $errors->has('seo_title') ? ' is-invalid' : '' }}"
                                            id="seo_title" placeholder="فارسی وارد شود">
                                        <div class="invalid-feedback">
                                            @error('seo_title')
                                            {{ $message }}
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="mb-1" for="meta_description"> توضیحات متا </label>
                                    <textarea id="meta_description" name="meta_description"
                                        class="form-control {{ $errors->has('meta_description') ? ' is-invalid' : '' }}">{{ old('meta_description') }}</textarea>
                                    <div class="invalid-feedback">
                                        @error('meta_description')
                                        {{ $message }}
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="mb-1" for="meta_keywords"> کلیدواژه های متا </label>
                                    <textarea id="meta_keywords" placeholder="با , جدا شود" name="meta_keywords"
                                        class="form-control {{ $errors->has('meta_keywords') ? ' is-invalid' : '' }}">{{ old('meta_keywords') }}</textarea>
                                    <div class="invalid-feedback">
                                        @error('meta_keywords')
                                        {{ $message }}
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.partials.master')
@section('admin.title', 'خبر ها')
@section('main')
    <a class="btn btn-success" href="{{ route('admin.articles.create') }}">
        <span class="material-icons">
            add
        </span> افزودن خبر
    </a>
    <div class="card mt-3">
        <div class="card-header d-flex justify-content-between">
            <div class="align-self-center">خبر ها</div>
            <div class="search w-25">
                <form action="{{ route('admin.articles.search') }}" method="GET">
                    <div class="has-search fg--search">
                        <button type="submit"><span class="mdi mdi-magnify form-control-feedback"></span></button>
                    <input name="q" value="{{ request()->input('q') ?? '' }}" type="text" class="form-control" placeholder="جستجو">
                    </div>

                </form>

            </div>

        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th>
                                تصویر
                            </th>
                            <th>
                                عنوان
                            </th>
                            <th>
                                وضعیت
                            </th>

                            <th>
                                تاریخ ایجاد
                            </th>
                            <th>
                                عملیات
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($articles as $key => $article)
                            <tr>
                                <td>
                                    <img width="60px" src="{{ thumb($article->image) }}" alt="عکس">
                                </td>
                                <td>
                                    {{ $article->title ?? '' }}
                                </td>
                                <td>
                                    @if ($article->published)
                                        <span class="badge badge-success badge-pill py-1 px-2"> منتشر شده </span>
                                    @else
                                        <span class="badge badge-warning text-white badge-pill py-1 px-2"> پیشنویس </span>
                                    @endif
                                </td>
                                <td>
                                    {{ verta($article->created_at)->format('j F Y | H:i') ?? '' }}
                                </td>
                                <td>
                                    <a class="btn btn-sm btn-success"
                                        href="{{ route('admin.articles.show', $article->slug) }}">
                                        <span class="material-icons">
                                            remove_red_eye
                                        </span> مشاهده
                                    </a>

                                    <a class="btn btn-sm btn-info"
                                        href="{{ route('admin.articles.edit', $article->slug) }}">
                                        <span class="material-icons">
                                            create
                                        </span> ویرایش
                                    </a>

                                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal"
                                        data-target="#delete-modal{{ $article->id }}">
                                        <span class="material-icons">
                                            delete
                                        </span> حذف
                                    </button>
                                </td>
                            </tr>
                            <div id="delete-modal{{ $article->id }}" class="modal fade">
                                <div class="modal-dialog modal-sm" role="document">
                                    <div class="modal-content">
                                        <div class="modal-body">
                                            <p class="text-black typography-subheading">آیا مطمئنید؟</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button class="btn btn-info" data-dismiss="modal" type="button">خیر</button>
                                            <form action="{{ route('admin.articles.destroy', $article->slug) }}"
                                                method="POST">
                                                @method('DELETE') @csrf
                                                <input class="btn text-white bg-info" type="submit" value="بلی">
                                            </form>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </tbody>
                </table>
                {{ $articles->onEachSide(1)->links() }}
            </div>


        </div>
    </div>
@endsection

resources/views/admin/articles/show.blade.php
@extends('admin.partials.master')
@section('admin.title','مشاهده خبر')
@section('main')

    <div class="card">
        <div class="card-header">
            مشاهده {{ $article->title  }}
        </div>

        <div class="card-body">
            <div class="mb-2">
                <h4>تصویر</h4>
                <img src="{{ $article->image  }}" class="w-50">
                <br>
                <br>
                <div>
                    @if($article->published)
                        <span class="badge badge-success badge-pill py-1 px-2"> منتشر شده </span>
                    @else
                        <span class="badge badge-warning text-white badge-pill py-1 px-2"> پیشنویس </span>
                    @endif
                        @if($article->featured)
                            <span class="badge badge-danger badge-pill py-1 px-2"> خبر ویژه </span>
                        @endif
                </div>
                <br>
                <br>
                {!! $article->body !!}
                <br>
                <br>
                <h4>نویسنده</h4>
                {{$article->user->name}}
                <br>
                <br>
                <h4>دسته بندی</h4>
                {{$article->category->name}}
                <br>
                <br>
                <h4>چکیده</h4>
                {{$article->excerpt}}
                <br>
                <br>
                <h4>برچسب ها</h4>
                {{$article->tagsToString()}}

                <br>
                <br>

                <h4>عنوان سئو</h4>
                {{$article->seo_title}}
                <br>
                <br>
                <h4>کلیدواژه های متا</h4>
                {{$article->meta_keywords}}
                <br>
                <br>

                <h4>توضیحات متا</h4>
                {{$article->meta_description}}
                <br>

                <h4> ادرس صفحه -> <a href="{{ route('site.articles.show', $article)}}">لینک</a></h4>


                <br>
                <a style="margin-top:20px;" class="btn btn-info" href="{{ url()->previous() }}">
                <span class="material-icons">
                    toc
                    </span> برگشت به لیست
                </a>
            </div>
        </div>
    </div>
@endsection