routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;

Route::group(['middleware' => ['auth', 'check_role'], 'prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');

    Route::resource('users', 'UserController');
    Route::delete('users_mass_destroy', 'UserController@massDestroy')->name('users.mass_destroy');

    Route::resource('roles', 'RoleController');
    Route::delete('roles_mass_destroy', 'RoleController@massDestroy')->name('roles.mass_destroy');

    Route::resource('permissions', 'PermissionController');
    Route::delete('permissions_mass_destroy', 'PermissionController@massDestroy')->name('permissions.mass_destroy');

    Route::get('articles/search', 'ArticleController@search')->name('articles.search');
    Route::resource('articles', 'ArticleController');

    Route::resource('categories', 'CategoryController');

    Route::resource('pages', 'PageController');

    Route::resource('menus', 'MenuController');

    Route::resource('tools', 'ToolController');

    Route::resource('slides', 'SlideController');

    Route::resource('comments', 'CommentController');

    Route::resource('messages', 'MessageController');

    Route::get('complaints/search', 'ComplaintController@search')->name('complaints.search');
    Route::resource('complaints', 'ComplaintController');

    Route::get('file-manager', 'FileManagerController@index')->name('file-manager');

    Route::group(['prefix' => 'filemanager'], function () {
        Lfm::routes();
    });

    Route::get('attachments/{filename}', function ($filename) {
        $full_path = storage_path('app/attachments/' . $filename);

        if (!File::exists($full_path)) {
            abort(404);
        }

        $file = File::get($full_path);
        $type = File::mimeType($full_path);

        return response($file, 200)->header("Content-Type", $type);
    })->name('attachment');
});

Route::group(['as' => 'site.', 'namespace' => 'Site', 'middleware' => 'visit'], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::get('/complaint', 'ComplaintController@create')->name('complaint');
    Route::post('/complaints', 'ComplaintController@store')->name('complaints.store');

    Route::get('pages/{page}', 'PageController@show')->name('pages.show');

    Route::get('articles/search', 'ArticleController@search')->name('articles.search');
    Route::get('articles/{article}', 'ArticleController@show')->name('articles.show');
    Route::get('articles', 'ArticleController@index')->name('articles.index');
    Route::post('articles/{article}/comments', 'CommentController@store')->name('comments.store');

    Route::get('tags/{tag}', 'TagController@show')->name('tags.show');

    Route::get('categories/{category}', 'CategoryController@show')->name('categories.show');

    Route::post('messages', 'MessageController@store')->name('messages.store');
});

Route::group(['middleware' => 'auth', 'namespace' => 'Auth'], function () {

    Route::post('/logout', 'AuthController@logout')->name('logout');
});


Route::get('test', function () {
    return 'true';
});

resources/views/admin/partials/header.blade.php
<nav class="admin-nav fixed-top navbar navbar-dark navbar-full bg-primary doc-navbar-permanent">
    <button aria-controls="navdrawerDefault" data-breakpoint="lg" data-type="permanent" aria-expanded="false"
        aria-label="Toggle Navdrawer" class="navbar-toggler d-lg-none" data-target="#navdrawerDefault"
        data-toggle="navdrawer"><span class="navbar-toggler-icon"></span></button>
    <ul class="navbar-nav justify-content-end">
        <li class="nav-item align-self-center flex-grow-1">کانون وکلا استان بوشهر</li>
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                {{ auth()->user()->name }}
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{{ route('site.home') }}"> <span
                        class="material-icons ml-1">person</span>پروفایل</a>
                <form class="" id="logout" method="post" action="{{ route('logout') }}">
                    @csrf
                    <button type="submit" class="dropdown-item">
                        <span class="material-icons">power_settings_new</span>
                        خروج
                    </button>
                </form>
            </div>
        </li>

    </ul>
</nav>

resources/views/admin/partials/master.blade.php
@extends('layouts.app')
@section('title')
    پنل مدیریت - @yield('admin.title')
@endsection
@section('content')

    @include('admin.partials.header')
    @include('admin.partials.sidebar')

    <div class="mt-5 py-4 px-3 doc-navbar-permanent">
        @include('layouts.flash-message')
        @yield('main')
    </div>

@endsection

resources/views/admin/partials/sidebar.blade.php
@php
use Illuminate\Support\Str;

function checkRoute($name) {
if(Route::current() && Str::contains(Route::current()->getName(),$name))
echo'active';
}
@endphp


<div aria-hidden="true" class="navdrawer navdrawer-right navdrawer-permanent-lg" id="navdrawerDefault" tabindex="-1">
    <div class="navdrawer-content">
        <div class="navdrawer-header">
            <a class="navbar-brand px-0" href="{{ route('admin.dashboard') }}">پنل مدیریت</a>
        </div>
        <nav class="navdrawer-nav">
            <a target="_blank" class="nav-item nav-link" href="{{ route('site.home') }}"><i
                    class="material-icons mr-3">home</i>
                صفحه اصلی</a>
        </nav>
        <div class="navdrawer-divider"></div>
        <nav class="navdrawer-nav">
            <a class="nav-item nav-link {{ checkRoute('categories.') }}" href="{{ route('admin.categories.index') }}"><i
                    class="material-icons mr-3">dialpad</i>
                دسته بندی ها</a>
            <a class="nav-item nav-link {{ checkRoute('articles.') }}" href="{{ route('admin.articles.index') }}"><i
                    class="material-icons mr-3">article</i>
                اخبار</a>
            <a class="nav-item nav-link {{ checkRoute('comments.') }}" href="{{ route('admin.comments.index') }}"><i
                    class="material-icons mr-3">comment</i>
                <span>نظرات</span>
                @if ($countOfNewComments > 0)
                    <span class="badge badge-info badge-pill float-left">{{ $countOfNewComments }}</span>
                @endif

            </a>
            <a class="nav-item nav-link {{ checkRoute('slides.') }}" href="{{ route('admin.slides.index') }}"><i
                    class="material-icons mr-3">view_carousel</i>
                اسلاید ها</a>
            <a class="nav-item nav-link {{ checkRoute('users.') }}" href="{{ route('admin.users.index') }}"><i
                    class="material-icons mr-3">groups</i> کاربران</a>
            <a class="nav-item nav-link {{ checkRoute('messages.') }}" href="{{ route('admin.messages.index') }}"><i
                    class="material-icons mr-3">forum</i>
                <span>پیام ها</span>
                @if ($countOfNewMessages > 0)
                    <span class="badge badge-info badge-pill float-left">{{ $countOfNewMessages }}</span>
                @endif
            </a>
            <a class="nav-item nav-link {{ checkRoute('complaints.') }}" href="{{ route('admin.complaints.index') }}"><i
                    class="material-icons mr-3">assignment_late</i>
                <span>شکایات</span>
                @if ($countOfNewComplaints > 0)
                    <span class="badge badge-info badge-pill float-left">{{ $countOfNewComplaints }}</span>
                @endif
            </a>

        </nav>
        <div class="navdrawer-divider"></div>
        <div class="navdrawer-subheader">پیشرفته</div>
        <nav class="navdrawer-nav">
            <a class="nav-item nav-link {{ checkRoute('permissions.') }}"
                href="{{ route('admin.permissions.index') }}"><i class="material-icons mr-3">rule</i>
                دسترسی ها</a>
            <a class="nav-item nav-link {{ checkRoute('roles.') }}" href="{{ route('admin.roles.index') }}"><i
                    class="material-icons mr-3">admin_panel_settings</i>
                نقش ها</a>
            <a class="nav-item nav-link {{ checkRoute('menus.') }}" href="{{ route('admin.menus.index') }}"><i
                    class="material-icons mr-3">menu</i>
                ساخت منو</a>
            <a class="nav-item nav-link {{ checkRoute('pages.') }}" href="{{ route('admin.pages.index') }}"><i
                    class="material-icons mr-3">menu_book</i>
                برگه ها</a>
            <a class="nav-item nav-link {{ checkRoute('tools.') }}" href="{{ route('admin.tools.index') }}"><i
                    class="material-icons mr-3">view_module</i>
                منوی کارتی</a>
            <a class="nav-item nav-link {{ checkRoute('file-manager') }}" href="{{ route('admin.file-manager') }}"><i
                    class="material-icons mr-3">folder</i>
                مدیریت فایل</a>
        </nav>
    </div>
</div>