routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Route;
use UniSharp\LaravelFilemanager\Lfm;

Route::group(['middleware' => ['auth', 'check_role'], 'prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');

    Route::resource('users', 'UserController');
    Route::delete('users_mass_destroy', 'UserController@massDestroy')->name('users.mass_destroy');

    Route::resource('roles', 'RoleController');
    Route::delete('roles_mass_destroy', 'RoleController@massDestroy')->name('roles.mass_destroy');

    Route::resource('permissions', 'PermissionController');
    Route::delete('permissions_mass_destroy', 'PermissionController@massDestroy')->name('permissions.mass_destroy');

    Route::get('articles/search', 'ArticleController@search')->name('articles.search');
    Route::resource('articles', 'ArticleController');

    Route::resource('categories', 'CategoryController');

    Route::resource('pages', 'PageController');

    Route::resource('menus', 'MenuController');

    Route::resource('tools', 'ToolController');

    Route::resource('slides', 'SlideController');

    Route::resource('comments', 'CommentController');

    Route::resource('messages', 'MessageController');

    Route::get('complaints/search', 'ComplaintController@search')->name('complaints.search');
    Route::resource('complaints', 'ComplaintController');

    Route::get('file-manager', 'FileManagerController@index')->name('file-manager');

    Route::group(['prefix' => 'filemanager'], function () {
        Lfm::routes();
    });

    Route::get('attachments/{filename}', function ($filename) {
        $full_path = storage_path('app/attachments/' . $filename);

        if (!File::exists($full_path)) {
            abort(404);
        }

        $file = File::get($full_path);
        $type = File::mimeType($full_path);

        return response($file, 200)->header("Content-Type", $type);
    })->name('attachment');
});

Route::group(['as' => 'site.', 'namespace' => 'Site', 'middleware' => 'visit'], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::get('/complaint', 'ComplaintController@create')->name('complaint');
    Route::post('/complaints', 'ComplaintController@store')->name('complaints.store');

    Route::get('pages/{page}', 'PageController@show')->name('pages.show');

    Route::get('articles/search', 'ArticleController@search')->name('articles.search');
    Route::get('articles/{article}', 'ArticleController@show')->name('articles.show');
    Route::get('articles', 'ArticleController@index')->name('articles.index');
    Route::post('articles/{article}/comments', 'CommentController@store')->name('comments.store');

    Route::get('tags/{tag}', 'TagController@show')->name('tags.show');

    Route::get('categories/{category}', 'CategoryController@show')->name('categories.show');

    Route::post('messages', 'MessageController@store')->name('messages.store');
});

Route::group(['middleware' => 'auth', 'namespace' => 'Auth'], function () {

    Route::post('/logout', 'AuthController@logout')->name('logout');
});


Route::get('test', function () {
    return 'true';
});

app/Http/Controllers/Site/ArticleController.php
<?php

namespace App\Http\Controllers\Site;

use App\Article;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    public function index()
    {
        $articles = Article::where("published","=","1")->latest()->paginate(10);
        return view('site.article.index', compact('articles'));
    }

    public function show(Article $article)
    {
        $article->sortedComments('desc');
        return view('site.article.show', compact('article'));
    }

    public function search(Request $request)
    {
        $articles = Article::where('title', 'LIKE', "%$request->q%")->latest()->paginate(10);
        $articles->appends(['q' => $request->q]);
        return view('site.article.index', compact('articles'));
    }
}

app/Http/Controllers/Site/CategoryController.php
<?php

namespace App\Http\Controllers\Site;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function show(Category $category)
    {
//        return $category->articles()->with('category')->get();
        $catarticles = $category->articles()->get(); ;
        return view('site.categories.index', compact('catarticles'));
//        return $category->articles()->get();
       // TODO: set view
    }
}

app/Http/Controllers/Site/CommentController.php
<?php

namespace App\Http\Controllers\Site;

use App\Article;
use App\Comment;
use App\Http\Controllers\Controller;
use App\Http\Requests\site\StoreCommentRequest;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    public function store(StoreCommentRequest $request,Article $article)
    {
        $data =  $request->all();
        $data['article_id'] = $article->id;
        $comment = Comment::create($data);
        if ($comment){
            return redirect()->route('site.articles.show',$article)->with(['msg' => 'نظر شما با موفقیت ثبت شد']);
        }
        return redirect()->route('site.articles.show',$article)->with(['msg' => 'نظر شما ثبت نشد']);
    }

}

app/Http/Controllers/Site/ComplaintController.php
<?php

namespace App\Http\Controllers\Site;

use App\Attachment;
use App\Complaint;
use App\Http\Controllers\Controller;
use App\Http\Requests\Site\StoreComlaintRequest;
use Illuminate\Http\Request;

class ComplaintController extends Controller
{
    public function create()
    {
        return view('site.complaint.store');
    }

    public function store(StoreComlaintRequest $request)
    {
        $data = $request->all();
        $data['code'] = generate_complaint_code();

        $valid_extensions = [
            'jpg',
            'jpeg',
            'png',
            'pdf',
            'doc',
            'docx'
        ];

        if ($request->hasFile('attachments')) {
            foreach ($request->file('attachments') as $file) {

                $size = ($file->getSize() / 1024);
                $extension = $file->extension();

                if (!in_array($extension, $valid_extensions)) {
                    return redirect()->route('site.complaint')->with('err', 'فرمت فایل انتخابی مجاز نمی باشد.');
                }

                if ($size > 700) {
                    return redirect()->route('site.complaint')->with('err', 'فایل شما بیشتر از 700 کیلوبایت می باشد.');
                }

                $file->store('attachments');
                $complaint = Complaint::create($data);
                $complaint->attachments()->save(new Attachment(['filename' => $file->hashName()]));
            }

        } else {
            $complaint = Complaint::create($data);
        }

        return redirect()->route('site.complaint')->with('msg', 'شکایت شما با موفقیت ثبت شد.' . ' کد پیگیری شما ' . $complaint->code . ' می باشد.');
    }

}

app/Http/Controllers/Site/HomeController.php
<?php

namespace App\Http\Controllers\Site;

use App\Article;
use App\Http\Controllers\Controller;
use App\Slide;
use App\Tool;

class HomeController extends Controller
{

    public function index()
    {
        $tools = Tool::orderBy('order', 'asc')->get();
        $slides = Slide::orderBy('order', 'asc')->get();
        $articles = Article::where("published","=","1")->latest()->take(8)->get();
        return view('site.home.index', compact('tools','slides','articles'));
    }
}

app/Http/Controllers/Site/MessageController.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class MessageController extends Controller
{
    public function store(Request $request)
    {

    }
}

app/Http/Controllers/Site/PageController.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Controller;
use App\Page;
use Illuminate\Http\Request;

class PageController extends Controller
{
    public function show(Page $page)
    {
        return view('site.page', compact('page'));
    }
}

app/Http/Controllers/Site/TagController.php
<?php

namespace App\Http\Controllers\Site;

use App\Article;
use App\Http\Controllers\Controller;
use App\Tag;

class TagController extends Controller
{
    public function show(Tag $tag)
    {
        return Article::withAnyTags([$tag->name])->get();
    }
}

app/Http/Livewire/Site/ComplaintSearch.php
<?php

namespace App\Http\Livewire\Site;

use App\Complaint;
use Livewire\Component;

class ComplaintSearch extends Component
{
    public $code;
    public $captcha;

    public function search()
    {
        $this->validate([
            'code' => 'required',
            'captcha' => 'captcha',
        ]);

        $peygiri = Complaint::where('code', $this->code)->first();

        if ($peygiri) {
            session()->flash('msg', 'وضعیت شکایت شما: ' . Complaint::translateStatus($peygiri->status));
        } else {
            session()->flash('err', 'کد پیگیری وارد شده اشتباه است');
        }
    }

    public function render()
    {
        return view('livewire.site.complaint-search');
    }
}

app/Http/Livewire/Site/Login.php
<?php

namespace App\Http\Livewire\Site;

use Illuminate\Support\Facades\Auth;
use Livewire\Component;

class Login extends Component
{
    public $email;
    public $password;

    // public function updated($field)
    // {
    //     $this->validateOnly($field, [
    //         'email' => 'required|email',
    //         'password' => 'required|min:6',
    //     ]);

    // }

    public function loginUser()
    {
        $validatedData = $this->validate([
            'email' => 'required|email',
            'password' => 'required|min:6',
        ]);

        $loginTry = Auth::attempt($validatedData);

        if ($loginTry) {

            /**
             * @var \App\User $user
             */

            $user = auth()->user();

            if (!$user->roles()->pluck('name')->contains('user'))
                $this->redirect('/admin');
            else
                $this->redirect('/');
        } else {
            session()->flash('err', 'اطلاعات وارد شده اشتباه است');
        }
    }

    public function render()
    {
        return view('livewire.site.login');
    }
}

app/Http/Livewire/Site/Register.php
<?php

namespace App\Http\Livewire\Site;

use App\User;
use Illuminate\Validation\ValidationException;
use Livewire\Component;

class Register extends Component
{
    public $name;
    public $email;
    public $password;
    public $password_confirmation;

    public function updated($field)
    {
            $this->validateOnly($field, [
                'name' => 'required|min:6',
                'email' => 'required|email|unique:users',
                'password' => 'required|min:6',
                'password_confirmation' => 'required|same:password',
            ]);

    }

    public function saveUser()
    {
        $validatedData = $this->validate([
            'name' => 'required|min:6',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6',
            'password_confirmation' => 'required|same:password',
        ]);

        $validatedData['password'] = bcrypt($validatedData['password']);

        User::create($validatedData);

        $this->redirect('/');
    }

    public function render()
    {
        return view('livewire.site.register');
    }
}

resources/views/site/partials/footer.blade.php
<div class="footer">
    <div class="row ">
        <div class="col-md-3">
            <h5>آمار کاربران</h5>
            <div>امروز :{{ $statistics['today'] }}</div>
            <div>دیروز :{{ $statistics['yesterday'] }}</div>
            <div>هفته جاری :{{ $statistics['this_week'] }}</div>
            <div>هفته گذشته :{{ $statistics['last_week'] }}</div>
            <div>ماه جاری :{{ $statistics['this_month'] }}</div>
            <div>ماه گذشته :{{ $statistics['last_month'] }}</div>
            <div>بازدید کل :{{ $statistics['total'] }}</div>
        </div>
        <div class="col-md-3">
            <h5>پیوندهای مرتبط</h5>
            <div><a href="http://www.hamivakil.ir/" target="_blank">صندوق حمایت وکلا و کارگشایان دادگستری</a></div>
            <div><a href="http://www.dadiran.ir/" target="_blank">قوه قضائیه</a></div>
            <div><a href="http://icbar.ir/" target="_blank">کانون وکلای دادگستری مرکز</a></div>
            <div><a href="http://www.scoda.ir/" target="_blank">اتحادیه سراسری کانون های وکلای دادگستری ایران</a></div>
            <div><a href="http://www.rrk.ir/Default.aspx" target="_blank">روزنامه رسمی</a></div>
            <div><a href="http://www.dadsetani.ir/" target="_blank">دادستانی کل کشور</a></div>
        </div>
        <div class="col-md-3">
            <h5>نظرسنجی</h5>
        </div>
        <div class="col-md-3">
            <h5>تماس با ما</h5>
            <table>
                <tr>
                    <th>
                        <span class="material-icons">location_on</span>
                    </th>
                    <td>
                        آدرس : بوشهر، خیابان بهشت صادق، رو به روی خبرگزاری جمهوری اسلامی، کانون وکلای دادگستری استان
                        بوشهر

                    </td>
                </tr>
                <tr>
                    <th>
                        <span class="material-icons">local_post_office</span>
                    </th>
                    <td>
                        کد پستی: 59774-75149

                    </td>
                </tr>
                <tr>
                    <th>
                        <span class="material-icons">phone</span>
                    </th>
                    <td>
                        تلفن تماس: 3541929

                    </td>
                </tr>
                <tr>
                    <th>
                        <span class="material-icons">print</span>
                    </th>
                    <td>
                        فکس: 3541930

                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="copy-right d-block d-sm-flex justify-content-between text-center">
        <div>تمام حقوق این سایت متعلق به کانون وکلای استان بوشهر میباشد.</div>
        <div><a href="#"> طراحی و اجرا: حمیدرضا اکبرزاده </a></div>
    </div>

</div>

resources/views/site/partials/header.blade.php
<div class="d-md-flex pt-3 px-4 align-items-center">
    <div class="flex-grow-1 text-center text-md-right">
        <span>{{ \Hekmatinasser\Verta\Verta::now()->format('l j F Y') . ' | ' . \Carbon\Carbon::now()->format('l j F Y') }}</span>
    </div>


    <div class="login mt-2 mt-md-0">
        @guest
            <button type="button" class="btn btn-flat-info btn-sm " data-toggle="modal" data-target="#login-modal"
                    data-whatever="@mdo">
                <span class="material-icons ml-1">login</span>
                {{--<img src="https://img.icons8.com/material/21/law--v1.svg"/>--}}
                ورود

            </button>
            <button class="btn btn-info btn-sm" type="button" data-toggle="modal" data-target="#register-modal">
                <span class="material-icons ml-1">person_add</span>
                عضویت
            </button>

        @else



            @unlessrole('user')
                <a href="{{route('admin.dashboard')}}" class="btn btn-flat-info btn-sm">پنل مدیریت </a>
            @endunlessrole

            <div class="btn btn-info btn-sm dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown">
                    {{auth()->user()->name}}
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{{route('site.home')}}"> <span
                                class="material-icons ml-1">person</span>پروفایل</a>
                    <form class="" id="logout" method="post" action="{{route('logout')}}">
                        @csrf
                        <button type="submit" class="dropdown-item">
                            <span class="material-icons">power_settings_new</span>
                            خروج
                        </button>
                    </form>
                </div>
            </div>


        @endguest

    </div>

    <div class="search">
        <form action="{{ route('site.articles.search') }}" method="get">
            <div class="has-search fg--search">
                <button type="submit"><span class="mdi mdi-magnify form-control-feedback"></span></button>
                <input name="q" value="{{ request()->input('q') ?? '' }}" type="text" class="form-control" placeholder="جستجو">
            </div>

        </form>

    </div>


</div>


<div id="banner" class="mt-3 mt-md-0">
    <div class="d-flex justify-content-between align-items-end">
        <div class="logo"><a href="{{ route('site.home') }}"><img src="{{asset('img/kanoon.png')}}"></a></div>
        <div class="d-none d-sm-block mainBanner"><img src="{{asset('img/headerBackground.png')}}"></div>
    </div>

</div>

<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        @livewire('site.login')
    </div>
</div>

<div class="modal fade" id="register-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        @livewire('site.register')
    </div>
</div>

resources/views/site/partials/master.blade.php
@extends('layouts.app')
@section('title')
    @yield('site.title') - کانون وکلا استان بوشهر

@endsection



    @section('content')
        <div class="content">
        @include('site.partials.header')
        @include('site.partials.navbar')
        {{--<div class="container-fluid">--}}

        @yield('main')
        {{--</div>--}}
        </div>
        @include('site.partials.footer')
    @endsection

resources/views/site/partials/navbar.blade.php
<nav class="navbar navbar-expand-lg bg-primary text-white navbar-light">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">

            <li class="nav-item">
                <a class="nav-link" href="{{ route('site.home') }}">صفحه اصلی <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{{ route('site.articles.index') }}">اخبار <span class="sr-only">(current)</span></a>
            </li>

            @foreach ($menus as $menu)

                @if (count($menu->children))

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                            {{ $menu->title }}
                        </a>
                        <ul class="dropdown-menu">
                            @foreach ($menu->children as $child)

                                @if (count($child->children))

                                    <li class="dropdown">
                                        <a class="dropdown-item" href="#">{{ $child->title }}</a>
                                        <ul class="dropdown-menu">

                                            @foreach ($child->children as $child2)
                                                <li><a class="dropdown-item" href="{{ route('site.pages.show', $child2->page) }}">{{ $child2->title }}</a></li>
                                            @endforeach
                                        </ul>
                                    </li>

                                @else

                                    <li>
                                        <a class="dropdown-item"
                                            href="{{ route('site.pages.show', $child->page) }}">{{ $child->title }}
                                        </a>
                                    </li>

                                @endif
                            @endforeach

                        </ul>
                    </li>
                @else

                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('site.pages.show', $menu->page) }}">{{ $menu->title }}</a>
                    </li>

                @endif

            @endforeach
        </ul>
    </div>
</nav>